# Generated by Django 5.2 on 2025-05-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_category_newsletter_author_blogpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="featured_image",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
