# Generated by Django 5.2 on 2025-05-16 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_blogpost_featured_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="excerpt",
        ),
    ]
