# Generated by Django 5.2 on 2025-05-16 02:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_blogpost_content_remove_blogpost_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="excerpt",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
