# Generated by Django 5.2 on 2025-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_blogpost_content_blogpost_excerpt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="image",
            field=models.ImageField(
                blank=True,
                default="blog_images/eyes.png",
                null=True,
                upload_to="blog_images/",
            ),
        ),
    ]
